### ISSUE TITLE
Time stamps needs timezone

### ISSUE THREAD

**Issue by ebopalm** [Ericsson/eiffel-operations-extension#26]
The current way of defining timestamps does not capture the time zone in which it happaned. To have a correct computation of object states based on world wide events, time zone information must be added and catered for. I leave the part of suggesting a reasonable repesentation of the time zone information to others.

**Comment by ebopalm** [comment]
Maybe this issue should be recorded in the "Eiffel" repo instead. Pls. advise.

**Comment by d-stahl-ericsson** [comment]
Milliseconds since epoch are not influenced by time zones or daylight savings. They simply count the time elapsed since 00:00:00, January 1, 1970 UTC.

**Comment by ebopalm** [comment]
Excellent. Then this item is closed.
