### ISSUE TITLE
ACTIVITY_EXECUTION links in Operations Extension events

### ISSUE THREAD

**Issue by d-stahl-ericsson** [Ericsson/eiffel-operations-extension#38]
All Operations Extension events currently feature ACTIVITY_EXECUTION links. This seems fishy to me. What is the significance of this?

**Comment by erobged** [comment]
The thinking was that ,all CO events would link back to the previous activity events for traceability purposes.
The activity events & CO would be published by some entity or entities (e.g scripts , cloud orchestrator, Jenkins job etc..)
 When an activity completes (triggered - started - finished) a CO event is published after the finished event.
Think of it like this maybe ... a Jenkins job is triggered to deploy and artifact , the script or whatever starts and ends (performing the deployment) and then publishes an ArtifectDeployedEvent.

**Comment by d-stahl-ericsson** [comment]
But that use case is what we have CONTEXT for. I don't see what would motivate bringing in a completely new paradigm here?

**Comment by erobged** [comment]
great , if that is the case then we can remove ACTIVITY_EXECUTION and use CONTEXT for all CO events.

**Comment by erobged** [comment]
So , to move this forward Daniel , does this mean a pull request needs to be created ?
If so , will you create it or shall I ?

**Comment by d-stahl-ericsson** [comment]
Yes. As a rule, I think the more PRs are created by people who are not me, the better it is for Eiffel in the long run... :)

**Comment by erobged** [comment]
Hi @xvinosi-github ,
Daniel and I have reviewed the above.
When you get a moment would you please make the changes please and create a pull request ?
Regards,
Rob

**Comment by xvinosi-github** [comment]
Noticed that domainId field has been made mandatory, But this is not the case for Eiffel events.

**Comment by erobged** [comment]
@l-ohlen-ericsson ,
@xvinosi-github 

remove ACTIVITY_EXECUTION Link type and use CONTEXT for **all** CO events :

schema
.md
sample json.

**Comment by erobged** [comment]
Share usage examples with Lars..

**Comment by erobged** [comment]
ACTIVITY_EXECUTION Link removed for these events.
