### ISSUE TITLE
The use of Announcement events for operations

### ISSUE THREAD

**Issue by d-stahl-ericsson** [Ericsson/eiffel-operations-extension#40]
I'm not convinced it's a good idea to use Announcement events the way proposed in this extension. When we're introducing a bunch of semantically highly specific events to describe the lifecycle of a service, wouldn't it make sense to also extend that to incidents? AnnP is sort of a bucket event right now that can do basically anything, but it contains no syntax that will support automated parsing and interpretation of a specific incident. 

I would suggest that:
- Usage of AnnP should be narrowed, and pipeline incidents not be cited as an example for its use (this is only natural... as stated it's a bucket event for stuff happening that the protocol doesn't really cover, but as the protocol expands, the applicable domain of AnnP is reduced)
- Introduce something like ServiceIncidentOccurredEvent and ServiceIncidentAcknowledgedEvent, instead of AnnA. Then, as suggested in #39, you can use a SERVICE link to identify which service we're talking about, and an INCIDENT link from ServiceIncidentAcknowledgedEvent to ServiceIncidentOccurredEvent (AnnA currently includes no link that will help you understand what has been acknowledged).

**Comment by rogpers-ericsson** [comment]
I concur with the proposal on a specific event type for this.

**Comment by erobged** [comment]
1. Propose changing ServiceIncidentOccurredEvent to ServiceIncidentRaisedEvent.

2. Propose another event called a **ServiceIncidentCeasedEvent** to work with the ServiceIncidentRaised Event and ServiceIncidentAcknowledgedEvent.
ServiceIncidentRaisedEvent -> ServiceIncidentAcknowledgedEvent -> ServiceIncidentCeasedEvent.

**Comment by rogpers-ericsson** [comment]
:+1:

**Comment by erobged** [comment]
ok , starting to work in this 
ServiceIncidentRaisedEvent **ServIncR**
ServiceIncidentAcknowledgedEvent **ServIncA**
ServiceIncidentCeasedEvent **ServIncC**

**Comment by erobged** [comment]
@xvinosi-github 

EiffelAlertRaisedEvent (AlerR)
EiffelAlertAcknowledgedEvent (AlerA)
EiffelAlertCeasedEvent (AlerC)

**Comment by d-stahl-ericsson** [comment]
Edited post above. Let's not post intranet links on the Internet :)

**Comment by erobged** [comment]
Events defined ... pull request completed.
